---
title: "PUBH7462_Sepsis_ ICU Report"
author: "Ashley Farnum"
format: html
editor: visual
---

## ICU Status Report for Sepsis Patients

#### Time and Date of Report

```{r echo=FALSE, message=FALSE, warning=FALSE}
current_report_time <- Sys.time()
current_time_string <- format(current_report_time, "%Y-%m-%d %H:%M:%S")
current_time_string
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(googledrive)
## Calling drive_deauth() prevents R from trying to authenticate via a browser
## This is needed to
source("sepsis_monitor_functions.R")
drive_deauth()
file_link <- "https://drive.google.com/file/d/1cVTavibXqOJu8QGaWSsIoRh1mjUEPtk-/"

## All data up until now
new_data <- updateData(file_link)

## Include only most recent data
most_recent_data <- new_data %>%
  group_by(PatientID) %>%
  filter(obsTime == max(obsTime))
```

### Current Sepsis Patients

```{r echo=FALSE, message=FALSE, warning=FALSE}
#| echo: false
sepsis_table1<-most_recent_data <- new_data %>%
  group_by(PatientID) %>%
  filter(SepsisLabel == "1") %>%
  filter(obsTime == max(obsTime)) %>%
   select(PatientID, HR, Resp, Temp, obsTime)
sepsis_table1
```

### Plot of Sepsis Patients HR, Temp, and Resp Rate

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)

sepsis_plot1 <- new_data %>%
  group_by(PatientID) %>%
  filter(SepsisLabel == "1") 

ggplot(sepsis_plot1, aes(x = obsTime, y = Temp, group = PatientID)) +
  geom_point() +
  ggtitle("Complete History of Temperature for Sepsis Patients")

ggplot(sepsis_plot1, aes(x = obsTime, y = Resp, group = PatientID)) +
  geom_point() +
  ggtitle("Complete History of Respiratory Rate for Sepsis Patients")

ggplot(sepsis_plot1, aes(x = obsTime, y = HR, group = PatientID)) +
  geom_point() +
  ggtitle("Complete History of Heart Rate for Sepsis Patients")
  
```

### Change in Physiological Measurements Table for Sepsis Patients

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(knitr)
sepsis_phys_change<-new_data%>%
  group_by(PatientID) %>%
  filter(SepsisLabel == "1")%>%
   slice_tail(n = 2) %>%
  summarise(
    HR_change = last(HR) - first(HR),
    Temp_change = last(Temp) - first(Temp),
    Resp_change = last(Resp) - first(Resp)
  )

 sepsis_phys_change  
   
```
